- name: play level varable
  hosts: local
  connection: local
  Vars:
    COURSE: Ansible # equal to course=ansible in shell er refer $VAR or ${VAR}
    DURATION: 10HR
    TRAINER: Sivakumar
    TRAINER2: Raghunath
  tasks:
  - name: print course information
    ansible.builtin.debug:
    # vars should be surrounded by ""
      msg: "Hello {{COURSE}}, Course duration {{ DURATION}},trainer is {{ TRAINER }} the student is {{ TRAINER2 }}"

  - name: print course information again
    ansible.builtin.debug:
      msg: "Hello {{COURSE}}, Course duration {{ DURATION}},trainer is {{ TRAINER }} the student is {{ TRAINER2 }}"


