- name: play level variable
  hosts: local
  connection: local
  vars:
    COURSE: Devops
    DURATION: 10HR
    TRAINER: Shiva
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration {{ DURATION}},Trainer is {{ TRAINER}}"
    
  - name: print course information again
    #vars refarence should be surrounded by
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, course duraton {{ DURATION }}, trainer is {{ TRAINEE}}"