- name: variables from files
  hosts: local
  connection: local
  vars_files: # another yaml fils taking
  - course.yaml #this is file name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"