- name: ansible data types
  hosts: local
  connection: local
  tasks:
    DURATION: 120 # this is number
    COURSE: "DevOPS with Aws"
    IS_Live: true
    TOOLS: list[]
    - linux
    - shell
    - ansible
    