- name: ansible data types
  hosts: local
  connection: local
  vars:
    DURATION: 120 # this is number
    COURSE: "DevOPS with Aws"
    IS_LIVE: true
    TOOLS: #list[]
    - linux
    - shell
    - ansible
    CONCEPTS: # map or directory or object. refferes like {}
      CI: Jenkins
      SCRIPTING: "SHELL ANSIBLE, Terraform, PYthon"
 
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: " Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCETPS }} " 
    