- name: install nginx
  hosts: dynamic_frontend
  become: yes
  serial: 5  # excuting instances
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
# parallaly connceted fork
