- name: play level variable
  hosts: local
  connection: local
  vars:
    list1:  # lists defined -
    - apple
    - banana
    - grapes
    list2:
    - peach
    - plum
    - pear

  
    dict1:
      name: Leeroy Jenkins
      age: 25
      occupation: Astronaut

    dict2:
      location: Galway
      country: Ireland
      postcode: H71 1234

    COURSE: Devops
    DURATION: 10HR
    TRAINER: Shiva
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration {{ DURATION}},Trainer is {{ TRAINER}}"
    
  - name: print course information again
    #vars refarence should be surrounded by
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, course duraton {{ DURATION }}, trainer is {{ TRAINER }}"
  
  - name: combined of lists
    ansible.builtin.set_fact:
      merged_list: "{{ list1 + list2 }}"
  
  - name: Combine dict1 and dict2 into a merged_dict var
    ansible.builtin.set_fact:
      merged_dict: " {{ dict1 | combine(dict2) }} "
  
  - name: Show merged dictionary
      debug:
        var: merged_dict